### ISSUE TITLE
Error in AutonomousCorner.java

### ISSUE THREAD

**Issue by drakeot** [The-Charge/SulfuricAcid2021#16]
The error allows the code to build, but exits the simulation with "Robots should not quit, but yours did!" The stack trace is below:
```
Inside Catch
Error at java.base/java.util.Objects.requireNonNull(Objects.java:221): Unhandled exception: java.lang.NullPointerException
        at java.base/java.util.Objects.requireNonNull(Objects.java:221)
        at java.base/java.util.ImmutableCollections$Set12.<init>(ImmutableCollections.java:504)
        at java.base/java.util.Set.of(Set.java:697)
        at edu.wpi.first.wpilibj2.command.CommandGroupBase.requireUngrouped(CommandGroupBase.java:55)
        at edu.wpi.first.wpilibj2.command.SequentialCommandGroup.addCommands(SequentialCommandGroup.java:32)
        at frc.robot.commands.AutonomousCorner.<init>(AutonomousCorner.java:51)
        at frc.robot.RobotContainer.configureButtonBindings(RobotContainer.java:269)
        at frc.robot.RobotContainer.<init>(RobotContainer.java:114)
        at frc.robot.RobotContainer.<clinit>(RobotContainer.java:57)
        at frc.robot.Robot.robotInit(Robot.java:42)
        at edu.wpi.first.wpilibj.TimedRobot.startCompetition(TimedRobot.java:94)
        at edu.wpi.first.wpilibj.RobotBase.runRobot(RobotBase.java:335)
        at edu.wpi.first.wpilibj.RobotBase.lambda$startRobot$0(RobotBase.java:387)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by neuenfeldttj** [comment]
If you check out the AutonTesting branch, it has been fixed.
